# -*- coding: utf-8 -*-
"""LCA 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkZG_tsYpcdeqRsWGmJpD5Lm3prgzj4W
"""

import pandas as pd
df= pd.read_csv('/content/drive/MyDrive/Adult Data.csv.zip')

print(df.head)

print(df.describe)

print(df.columns)

print(df.info)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.size)

print("First 5 rows of dataset:")
print(df.head())

print(df.columns.tolist())

#Import Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import zipfile

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#last column is the target (income <=50K or >50K)
X = df.iloc[:, :-1].values   # all features
y = df.iloc[:, -1].values    # target

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

df.columns = [
    "age", "workclass", "fnlwgt", "education", "education_num",
    "marital_status", "occupation", "relationship", "race",
    "sex", "capital_gain", "capital_loss", "hours_per_week",
    "native_country", "income"
]

#Encode categorical features properly
label_encoders = {}

for col in df.columns:
    if df[col].dtype == "object":   # check if column is categorical
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

print("Encoded dataset head:")
print(df.head())
print("Data types:\n", df.dtypes)

#Features and target
X = df.drop("income", axis=1).values
y = df["income"].values

# Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train KNN classiffier model
knn = KNeighborsClassifier(n_neighbors=5)  # default k=5
knn.fit(X_train_scaled, y_train)

# Predictions
y_pred = knn.predict(X_test_scaled)

#Evaluate the Model
accuracy = accuracy_score(y_test, y_pred)
print("\n✅ Accuracy of KNN model:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))